# Generated by the release workflow in woksin/workstats. Do not edit by hand.
class Workstats < Formula
  desc "See where the work happened, without sending your work anywhere"
  homepage "https://github.com/woksin/workstats"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/woksin/workstats/releases/download/v1.2.0/workstats-macos-arm64.tar.gz"
      sha256 "4e5c0ae8425ea0556166f6bcc39902ffdc28ae0f128c5c70a192813ac771b461"
    end
    on_intel do
      url "https://github.com/woksin/workstats/releases/download/v1.2.0/workstats-macos-x86_64.tar.gz"
      sha256 "f135507defb209564152ff0f7155a5a5a1fdcdb2dd16a9427672c7a394f8a89b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/woksin/workstats/releases/download/v1.2.0/workstats-linux-arm64.tar.gz"
      sha256 "3aa1f8370a88d1d1aee1470655e19d3e9b23e6a4998bb48eb13d6e0933088a11"
    end
    on_intel do
      url "https://github.com/woksin/workstats/releases/download/v1.2.0/workstats-linux-x86_64.tar.gz"
      sha256 "4e38a4fbc835ba7956e399d8e925ccad89c459bef4a6bdfeae2e5af698cfa4a2"
    end
  end

  def install
    bin.install "workstats"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workstats --version")
  end
end
