# Generated by the release workflow in woksin/workstats. Do not edit by hand.
class Workstats < Formula
  desc "See where the work happened, without sending your work anywhere"
  homepage "https://github.com/woksin/workstats"
  version "1.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/woksin/workstats/releases/download/v1.5.0/workstats-macos-arm64.tar.gz"
      sha256 "8605eb29e503b24beb7f2ba8a179eef1fc5501f115bfb17e7be070668348c2cf"
    end
    on_intel do
      url "https://github.com/woksin/workstats/releases/download/v1.5.0/workstats-macos-x86_64.tar.gz"
      sha256 "c6aaa02e194dad93db18a135e60575d30d0e10a7d0134888b226a7cdfdb5fb77"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/woksin/workstats/releases/download/v1.5.0/workstats-linux-arm64.tar.gz"
      sha256 "f30b2aeb39a81e7e1eded3723aa64c2c0aeccce2d6f3f05c3efc07cbfd1358cd"
    end
    on_intel do
      url "https://github.com/woksin/workstats/releases/download/v1.5.0/workstats-linux-x86_64.tar.gz"
      sha256 "30d2392325ebfa20de58b6d12ed1670b023cd90e8858f1ea4bea6f568515fd0e"
    end
  end

  def install
    bin.install "workstats"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workstats --version")
  end
end
