# Generated by the release workflow in woksin/workstats. Do not edit by hand.
class Workstats < Formula
  desc "See where the work happened, without sending your work anywhere"
  homepage "https://github.com/woksin/workstats"
  version "1.11.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/woksin/workstats/releases/download/v1.11.0/workstats-macos-arm64.tar.gz"
      sha256 "eb0cdfd6ed34bab4e7b95cf0a37ce2a3f905c969dafd1a37053e6599069ab90f"
    end
    on_intel do
      url "https://github.com/woksin/workstats/releases/download/v1.11.0/workstats-macos-x86_64.tar.gz"
      sha256 "bf41cf59f885cd0d34e4e81bbb98cce842772ed7e00ed218ffa8c061803d44cc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/woksin/workstats/releases/download/v1.11.0/workstats-linux-arm64.tar.gz"
      sha256 "ea689cfe29f16826ba33d2fd0d78616010106a7702028748c2d1f4cd7332e409"
    end
    on_intel do
      url "https://github.com/woksin/workstats/releases/download/v1.11.0/workstats-linux-x86_64.tar.gz"
      sha256 "72a50da0010ccfcc746cbb772e670df919b51a1fe2167c4cb7308a8f18c88f31"
    end
  end

  def install
    bin.install "workstats"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workstats --version")
  end
end
